### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by eshacker** [idobsweb/detect-adblock#1]
Hey guys, I forked and created a simple page. Turns out it doesn't detect AdBlocker Plus. Any idea?

**Comment by eshacker** [comment]
![screenshot from 2016-02-19 16-50-05](https://cloud.githubusercontent.com/assets/16328967/13174161/ed8a703e-d729-11e5-85fa-ccb28bc796d0.png)

**Comment by eshacker** [comment]
Though online one works @ http://eshacker.github.io/detect-adblock/
![screenshot from 2016-02-19 17-01-37](https://cloud.githubusercontent.com/assets/16328967/13174281/af82ebd0-d72a-11e5-8888-eaf17870245e.png)

Tell me that this script doesn't work for local pages and only for online pages. :)

**Comment by mledoze** [comment]
Hello, I think this is it, the script does not work on local pages because I think Adblocker Plus does not work on local pages.

**Comment by eshacker** [comment]
> "Adblocker Plus does not work on local pages"
Yup that might be it.
